Colors = @{
	Command            = $PSStyle.Foreground.BrightYellow
	Comment            = $PSStyle.Foreground.BrightGreen
	ContinuationPrompt = $PSStyle.Foreground.BrightWhite
	Default            = $PSStyle.Foreground.BrightWhite
	Emphasis           = $PSStyle.Foreground.Cyan
	Error              = $PSStyle.Foreground.Red
	Keyword            = $PSStyle.Foreground.Magenta
	Member             = $PSStyle.Foreground.Cyan
	Number             = $PSStyle.Foreground.Magenta
	Operator           = $PSStyle.Foreground.White
	Parameter          = $PSStyle.Foreground.White
	Selection          = $PSStyle.Foreground.White + $PSStyle.Background.Cyan
	String             = $PSStyle.Foreground.Yellow
	Type               = $PSStyle.Foreground.Blue
	Variable           = $PSStyle.Foreground.Cyan
	InLinePrediction   = $PSStyle.Foreground.BrightYellow + $PSStyle.Background.BrightBlack
	InlinePredictionError = $PSStyle.Foreground.BrightRed + $PSStyle.Background.BrightBlack
	InlinePredictionInsert = $PSStyle.Foreground.BrightGreen + $PSStyle.Background.BrightBlack
	InlinePredictionRemove = $PSStyle.Foreground.BrightRed + $PSStyle.Background.BrightBlack
	InlinePredictionReplace = $PSStyle.Foreground.BrightYellow + $PSStyle.Background.BrightBlack
}
	    Command            = "$($ansiesc)[93m" # Yellow
			Comment            = "$($ansiesc)[32m" # Green
			ContinuationPrompt = "$($ansiesc)[37m" # White
			Default            = "$($ansiesc)[37m" # White
			Emphasis           = "$($ansiesc)[96m" # Cyan
			Error              = "$($ansiesc)[31m" # Red
			Keyword            = "$($ansiesc)[35m" # Magenta
			Member             = "$($ansiesc)[96m" # Cyan
			Number             = "$($ansiesc)[35m" # Magenta
			Operator           = "$($ansiesc)[37m" # White
			Parameter          = "$($ansiesc)[37m" # White
			Selection          = "$($ansiesc)[37;46m" # White on Cyan
			String             = "$($ansiesc)[33m" # Yellow
			Type               = "$($ansiesc)[34m" # Blue
			Variable           = "$($ansiesc)[96m" # Cyan